import type { Metadata } from "next";
import "../../public/CSS/reset.css"
import "../../public/CSS/globals.css";


export const metadata: Metadata = {
  title: "My Daily Routine",
  description: "Generated by Gabo and Sebax",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body >
        {children}
      </body>
    </html>
  );
}
